import SwiftUI

/// Where a constellation sits relative to the celestial equator — used to group
/// and filter the viewer. "Equatorial" means it straddles the equator and is
/// visible, at least in part, from both hemispheres.
enum SkyHemisphere: String, CaseIterable, Sendable {
    case northern = "Northern"
    case equatorial = "Equatorial"
    case southern = "Southern"
}

/// Curated, human-facing facts about one of the 88 IAU constellations. The
/// stick-figure geometry lives separately in the bundled line file (parsed into
/// `Constellation`); this is the descriptive layer that makes the viewer worth
/// browsing. Brightest-star and star counts are computed from the live catalog,
/// not stored here, so they always match what we actually render.
struct ConstellationInfo: Identifiable, Sendable {
    let abbr: String          // IAU abbreviation, e.g. "Ori"
    let name: String          // "Orion"
    let genitive: String      // "Orionis" — the form used in star names (α Orionis)
    let meaning: String       // what it depicts, in plain English
    let hemisphere: SkyHemisphere
    let family: String        // traditional grouping (Menzel families, lightly adapted)
    let blurb: String         // a sentence or two of lore / what to look for

    var id: String { abbr }
}

/// The authored catalog of all 88 constellations, plus lookup by abbreviation.
/// Families follow Menzel's eight traditional groupings (with the zodiac pulled
/// out whole for browsing), so the viewer can present them in meaningful sets
/// rather than one long alphabetical wall.
enum ConstellationCatalog {
    static func info(for abbr: String?) -> ConstellationInfo? {
        guard let abbr else { return nil }
        return byAbbr[abbr]
    }

    private static let byAbbr = Dictionary(
        all.map { ($0.abbr, $0) }, uniquingKeysWith: { a, _ in a })

    /// Family display order — roughly brightest/most-famous first.
    static let familyOrder = [
        "Zodiac", "Ursa Major", "Perseus", "Orion",
        "Hercules", "Heavenly Waters", "Bayer", "La Caille",
    ]

    static let all: [ConstellationInfo] = [
        // MARK: Zodiac
        .init(abbr: "Ari", name: "Aries", genitive: "Arietis", meaning: "The Ram",
              hemisphere: .northern, family: "Zodiac",
              blurb: "The first sign of the zodiac, marked by the golden-fleeced ram of Greek myth. Its small crook of stars led by Hamal once held the vernal equinox."),
        .init(abbr: "Tau", name: "Taurus", genitive: "Tauri", meaning: "The Bull",
              hemisphere: .northern, family: "Zodiac",
              blurb: "A V of stars forms the bull's face, anchored by red-orange Aldebaran. Home to two naked-eye star clusters: the Hyades and the dazzling Pleiades."),
        .init(abbr: "Gem", name: "Gemini", genitive: "Geminorum", meaning: "The Twins",
              hemisphere: .northern, family: "Zodiac",
              blurb: "The twin brothers Castor and Pollux, whose bright heads top two parallel lines of stars. The Geminid meteor shower radiates from here each December."),
        .init(abbr: "Cnc", name: "Cancer", genitive: "Cancri", meaning: "The Crab",
              hemisphere: .northern, family: "Zodiac",
              blurb: "The faintest zodiac constellation, a dim inverted Y. At its heart glitters the Beehive Cluster (M44), a swarm of stars visible to the naked eye under dark skies."),
        .init(abbr: "Leo", name: "Leo", genitive: "Leonis", meaning: "The Lion",
              hemisphere: .northern, family: "Zodiac",
              blurb: "A genuine lion shape: a backwards question mark (the Sickle) forms the mane, with bright Regulus at the lion's heart and Denebola marking the tail."),
        .init(abbr: "Vir", name: "Virgo", genitive: "Virginis", meaning: "The Maiden",
              hemisphere: .equatorial, family: "Zodiac",
              blurb: "The second-largest constellation, holding a goddess of the harvest. Blue-white Spica is her wheat-sheaf, and the Virgo Cluster of galaxies lies within her."),
        .init(abbr: "Lib", name: "Libra", genitive: "Librae", meaning: "The Scales",
              hemisphere: .southern, family: "Zodiac",
              blurb: "The only zodiac sign depicting an object, not a creature. Its stars were once the claws of Scorpius — names like Zubenelgenubi still mean 'southern claw'."),
        .init(abbr: "Sco", name: "Scorpius", genitive: "Scorpii", meaning: "The Scorpion",
              hemisphere: .southern, family: "Zodiac",
              blurb: "One of the few constellations that truly looks like its namesake — a curving tail tipped with a sting. The red supergiant Antares burns at its heart."),
        .init(abbr: "Sgr", name: "Sagittarius", genitive: "Sagittarii", meaning: "The Archer",
              hemisphere: .southern, family: "Zodiac",
              blurb: "A centaur archer whose brightest stars form the 'Teapot.' Aim past its spout toward the galactic centre, the richest patch of Milky Way in the sky."),
        .init(abbr: "Cap", name: "Capricornus", genitive: "Capricorni", meaning: "The Sea-Goat",
              hemisphere: .southern, family: "Zodiac",
              blurb: "A mythical goat with a fish's tail, drawn as a wide smiling triangle of faint stars. The smallest and one of the oldest zodiac figures."),
        .init(abbr: "Aqr", name: "Aquarius", genitive: "Aquarii", meaning: "The Water-Bearer",
              hemisphere: .equatorial, family: "Zodiac",
              blurb: "An ancient figure pouring a stream of water toward the southern fish. Faint but vast, set in a watery region of sky alongside Pisces and Cetus."),
        .init(abbr: "Psc", name: "Pisces", genitive: "Piscium", meaning: "The Fishes",
              hemisphere: .northern, family: "Zodiac",
              blurb: "Two fish tied tail-to-tail by a cord meeting at the star Alrescha. The vernal equinox — the Sun's spring crossing point — now lies within Pisces."),

        // MARK: Ursa Major family
        .init(abbr: "UMa", name: "Ursa Major", genitive: "Ursae Majoris", meaning: "The Great Bear",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "Home to the Big Dipper, the most recognised star pattern in the northern sky. Its 'Pointer' stars line up on Polaris and the way north."),
        .init(abbr: "UMi", name: "Ursa Minor", genitive: "Ursae Minoris", meaning: "The Little Bear",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "The Little Dipper, with Polaris — the North Star — fixed at the tip of its handle. The whole sky appears to wheel around this single point."),
        .init(abbr: "Dra", name: "Draco", genitive: "Draconis", meaning: "The Dragon",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "A long serpentine dragon coiling between the two Bears. Its star Thuban was the pole star of the ancient Egyptians, 4,700 years ago."),
        .init(abbr: "Boo", name: "Boötes", genitive: "Boötis", meaning: "The Herdsman",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "A kite-shaped figure anchored by Arcturus, the brightest star of the northern sky. Follow the Big Dipper's handle to 'arc to Arcturus.'"),
        .init(abbr: "CVn", name: "Canes Venatici", genitive: "Canum Venaticorum", meaning: "The Hunting Dogs",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "Two greyhounds held by Boötes as they chase the Great Bear. Sparse to the eye, but it holds the gorgeous Whirlpool Galaxy (M51)."),
        .init(abbr: "Com", name: "Coma Berenices", genitive: "Comae Berenices", meaning: "Berenice's Hair",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "Named for the shorn tresses of an Egyptian queen, this faint sprinkle is actually a nearby star cluster. The north galactic pole lies here."),
        .init(abbr: "CrB", name: "Corona Borealis", genitive: "Coronae Borealis", meaning: "The Northern Crown",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "A neat semicircle of seven stars — the jewelled crown of Ariadne, cast into the sky. It hosts the famous 'Blaze Star,' a recurrent nova."),
        .init(abbr: "Cam", name: "Camelopardalis", genitive: "Camelopardalis", meaning: "The Giraffe",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "A faint, sprawling giraffe invented in 1612 to fill the blank space near the pole. No star is brighter than 4th magnitude."),
        .init(abbr: "Lyn", name: "Lynx", genitive: "Lyncis", meaning: "The Lynx",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "Hevelius named it the Lynx because, he joked, you'd need a lynx's eyes to see its faint zigzag of stars at all."),
        .init(abbr: "LMi", name: "Leo Minor", genitive: "Leonis Minoris", meaning: "The Smaller Lion",
              hemisphere: .northern, family: "Ursa Major",
              blurb: "A small triangle of dim stars tucked between Leo and the Great Bear — a 17th-century invention with no ancient mythology of its own."),

        // MARK: Perseus family
        .init(abbr: "Cas", name: "Cassiopeia", genitive: "Cassiopeiae", meaning: "The Queen",
              hemisphere: .northern, family: "Perseus",
              blurb: "The vain queen, bound to her throne in a distinctive 'W' (or 'M') of five bright stars. Circumpolar from mid-northern latitudes — always above the horizon."),
        .init(abbr: "Cep", name: "Cepheus", genitive: "Cephei", meaning: "The King",
              hemisphere: .northern, family: "Perseus",
              blurb: "Cassiopeia's husband, drawn as a child's house with a peaked roof near the pole. Its star Delta Cephei gives its name to the Cepheid 'standard candles.'"),
        .init(abbr: "And", name: "Andromeda", genitive: "Andromedae", meaning: "The Chained Princess",
              hemisphere: .northern, family: "Perseus",
              blurb: "The princess chained to a rock as a sacrifice, rescued by Perseus. Holds the Andromeda Galaxy (M31), the most distant thing visible to the naked eye."),
        .init(abbr: "Per", name: "Perseus", genitive: "Persei", meaning: "The Hero",
              hemisphere: .northern, family: "Perseus",
              blurb: "The hero who slew Medusa, holding her severed head — marked by Algol, the 'Demon Star' that visibly winks every few days. Source of the Perseid meteors."),
        .init(abbr: "Peg", name: "Pegasus", genitive: "Pegasi", meaning: "The Winged Horse",
              hemisphere: .northern, family: "Perseus",
              blurb: "The flying horse, recognised by the Great Square — a huge near-perfect rectangle of stars marking his body. 51 Pegasi hosted the first exoplanet found round a Sun-like star."),
        .init(abbr: "Aur", name: "Auriga", genitive: "Aurigae", meaning: "The Charioteer",
              hemisphere: .northern, family: "Perseus",
              blurb: "A pentagon high overhead in winter, crowned by brilliant Capella. The charioteer is shown carrying a goat and her kids across his shoulder."),
        .init(abbr: "Tri", name: "Triangulum", genitive: "Trianguli", meaning: "The Triangle",
              hemisphere: .northern, family: "Perseus",
              blurb: "Simply three stars in a slim triangle, known since antiquity. It contains the Triangulum Galaxy (M33), a face-on spiral and a near neighbour of our own."),
        .init(abbr: "Lac", name: "Lacerta", genitive: "Lacertae", meaning: "The Lizard",
              hemisphere: .northern, family: "Perseus",
              blurb: "A faint zigzag of stars between Cygnus and Andromeda, invented by Hevelius. Sometimes called 'Little Cassiopeia' for its small W shape."),
        .init(abbr: "Cet", name: "Cetus", genitive: "Ceti", meaning: "The Sea Monster",
              hemisphere: .equatorial, family: "Perseus",
              blurb: "The whale-like monster sent to devour Andromeda. The fourth-largest constellation, home to Mira, the first known long-period variable star."),

        // MARK: Orion family
        .init(abbr: "Ori", name: "Orion", genitive: "Orionis", meaning: "The Hunter",
              hemisphere: .equatorial, family: "Orion",
              blurb: "The grandest constellation: the hunter striding with belt and sword. Red Betelgeuse and blue Rigel bracket the three Belt stars, below which glows the Orion Nebula."),
        .init(abbr: "CMa", name: "Canis Major", genitive: "Canis Majoris", meaning: "The Greater Dog",
              hemisphere: .southern, family: "Orion",
              blurb: "Orion's larger hunting dog, blazing with Sirius — the brightest star in all the night sky. Follow Orion's Belt down-left to find it."),
        .init(abbr: "CMi", name: "Canis Minor", genitive: "Canis Minoris", meaning: "The Lesser Dog",
              hemisphere: .equatorial, family: "Orion",
              blurb: "Orion's smaller dog, essentially just two stars led by bright Procyon. With Sirius and Betelgeuse it completes the Winter Triangle."),
        .init(abbr: "Mon", name: "Monoceros", genitive: "Monocerotis", meaning: "The Unicorn",
              hemisphere: .equatorial, family: "Orion",
              blurb: "A faint unicorn set in the Milky Way inside the Winter Triangle. Dim to the eye, but rich in nebulae including the Rosette and the Cone."),
        .init(abbr: "Lep", name: "Lepus", genitive: "Leporis", meaning: "The Hare",
              hemisphere: .southern, family: "Orion",
              blurb: "A hare crouching beneath Orion's feet, forever fleeing his hunting dogs. A small but distinct figure with a bow-tie of stars."),

        // MARK: Hercules family
        .init(abbr: "Her", name: "Hercules", genitive: "Herculis", meaning: "The Strongman",
              hemisphere: .northern, family: "Hercules",
              blurb: "The kneeling hero, recognised by the 'Keystone' — a lopsided square of four stars. Its edge holds M13, the finest globular cluster of the northern sky."),
        .init(abbr: "Lyr", name: "Lyra", genitive: "Lyrae", meaning: "The Lyre",
              hemisphere: .northern, family: "Hercules",
              blurb: "Orpheus's harp, a small parallelogram beside brilliant blue-white Vega. Between two of its stars lies the famous Ring Nebula (M57)."),
        .init(abbr: "Cyg", name: "Cygnus", genitive: "Cygni", meaning: "The Swan",
              hemisphere: .northern, family: "Hercules",
              blurb: "A swan flying down the Milky Way, also called the Northern Cross. Deneb marks its tail; the band of the galaxy splits through it in the Great Rift."),
        .init(abbr: "Aql", name: "Aquila", genitive: "Aquilae", meaning: "The Eagle",
              hemisphere: .equatorial, family: "Hercules",
              blurb: "The eagle that carried Zeus's thunderbolts, soaring along the Milky Way. Its bright star Altair completes the Summer Triangle with Vega and Deneb."),
        .init(abbr: "Sge", name: "Sagitta", genitive: "Sagittae", meaning: "The Arrow",
              hemisphere: .northern, family: "Hercules",
              blurb: "The third-smallest constellation: a tiny but convincing arrow in flight, lodged in the Milky Way between Aquila and the swan's neck."),
        .init(abbr: "Vul", name: "Vulpecula", genitive: "Vulpeculae", meaning: "The Little Fox",
              hemisphere: .northern, family: "Hercules",
              blurb: "A faint fox inside the Summer Triangle, invented by Hevelius. It holds the Dumbbell Nebula (M27), the first planetary nebula ever discovered."),
        .init(abbr: "Sct", name: "Scutum", genitive: "Scuti", meaning: "The Shield",
              hemisphere: .southern, family: "Hercules",
              blurb: "A small shield commemorating a Polish king, set against one of the brightest star-clouds of the Milky Way, the Scutum Star Cloud."),
        .init(abbr: "Oph", name: "Ophiuchus", genitive: "Ophiuchi", meaning: "The Serpent-Bearer",
              hemisphere: .equatorial, family: "Hercules",
              blurb: "A healer wrestling a great serpent — the unofficial 13th sign of the zodiac, which the Sun passes through each December. Holds Barnard's Star, the fastest-moving star known."),
        .init(abbr: "Ser", name: "Serpens", genitive: "Serpentis", meaning: "The Serpent",
              hemisphere: .equatorial, family: "Hercules",
              blurb: "The only constellation split in two: the serpent's head (Caput) and tail (Cauda) on either side of Ophiuchus, who grips it. The Eagle Nebula lies in the tail."),
        .init(abbr: "Hya", name: "Hydra", genitive: "Hydrae", meaning: "The Water Snake",
              hemisphere: .equatorial, family: "Hercules",
              blurb: "The largest constellation of all, a vast snake winding a quarter of the way around the sky. Only its lone heart-star Alphard is at all bright."),
        .init(abbr: "Crt", name: "Crater", genitive: "Crateris", meaning: "The Cup",
              hemisphere: .southern, family: "Hercules",
              blurb: "The goblet of Apollo, a faint chalice of stars riding on the back of Hydra, beside the crow Corvus."),
        .init(abbr: "Crv", name: "Corvus", genitive: "Corvi", meaning: "The Crow",
              hemisphere: .southern, family: "Hercules",
              blurb: "A small, distinct sail-shaped quadrilateral of stars — the crow that Apollo set in the sky. It rides Hydra's back beside the Cup."),
        .init(abbr: "Sex", name: "Sextans", genitive: "Sextantis", meaning: "The Sextant",
              hemisphere: .equatorial, family: "Hercules",
              blurb: "A faint scattering of stars honouring Hevelius's astronomical sextant, lost when his observatory burned. Nothing here is brighter than 5th magnitude."),
        .init(abbr: "Cen", name: "Centaurus", genitive: "Centauri", meaning: "The Centaur",
              hemisphere: .southern, family: "Hercules",
              blurb: "A brilliant southern centaur whose foot is Alpha Centauri, the closest star system to the Sun. It surrounds the Southern Cross and holds the giant Omega Centauri cluster."),
        .init(abbr: "Cru", name: "Crux", genitive: "Crucis", meaning: "The Southern Cross",
              hemisphere: .southern, family: "Hercules",
              blurb: "The smallest constellation, but one of the most famous — the compact Southern Cross that points the way to the south celestial pole. It graces several national flags."),
        .init(abbr: "Lup", name: "Lupus", genitive: "Lupi", meaning: "The Wolf",
              hemisphere: .southern, family: "Hercules",
              blurb: "A wolf speared by the neighbouring Centaur, set in a rich field of the southern Milky Way between Scorpius and Centaurus."),
        .init(abbr: "Ara", name: "Ara", genitive: "Arae", meaning: "The Altar",
              hemisphere: .southern, family: "Hercules",
              blurb: "The altar on which the gods swore their alliance before the war with the Titans, drawn just south of Scorpius's sting."),
        .init(abbr: "TrA", name: "Triangulum Australe", genitive: "Trianguli Australis", meaning: "The Southern Triangle",
              hemisphere: .southern, family: "Hercules",
              blurb: "A neat, bright triangle near the south pole — more distinct than its northern namesake, with three stars of nearly equal brightness."),
        .init(abbr: "CrA", name: "Corona Australis", genitive: "Coronae Australis", meaning: "The Southern Crown",
              hemisphere: .southern, family: "Hercules",
              blurb: "A delicate arc of stars beneath Sagittarius, the southern counterpart to the Northern Crown, set against a dark nebula-rich region."),

        // MARK: Heavenly Waters
        .init(abbr: "Del", name: "Delphinus", genitive: "Delphini", meaning: "The Dolphin",
              hemisphere: .northern, family: "Heavenly Waters",
              blurb: "A charming little dolphin leaping from the Milky Way, its compact diamond-and-tail shape nicknamed 'Job's Coffin.'"),
        .init(abbr: "Equ", name: "Equuleus", genitive: "Equulei", meaning: "The Little Horse",
              hemisphere: .northern, family: "Heavenly Waters",
              blurb: "The second-smallest constellation: just the head of a foal beside Pegasus, made of a few faint stars and easily overlooked."),
        .init(abbr: "Eri", name: "Eridanus", genitive: "Eridani", meaning: "The River",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "A long celestial river meandering from Orion's foot far into the southern sky, ending at brilliant Achernar — the sixth-largest constellation."),
        .init(abbr: "PsA", name: "Piscis Austrinus", genitive: "Piscis Austrini", meaning: "The Southern Fish",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "The fish drinking the water poured by Aquarius, marked by the lone bright star Fomalhaut — the 'Solitary One' of the autumn sky."),
        .init(abbr: "Car", name: "Carina", genitive: "Carinae", meaning: "The Keel",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "The keel of the great ship Argo, holding Canopus, the second-brightest star in the sky, and the colossal Carina Nebula around the volatile star Eta Carinae."),
        .init(abbr: "Pup", name: "Puppis", genitive: "Puppis", meaning: "The Stern",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "The stern of the dismembered ship Argo, drifting through a brilliant stretch of the southern Milky Way thick with star clusters."),
        .init(abbr: "Vel", name: "Vela", genitive: "Velorum", meaning: "The Sails",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "The sails of the ship Argo, set in the rich southern Milky Way. It holds the Vela supernova remnant and a 'False Cross' that fools sailors hunting for Crux."),
        .init(abbr: "Pyx", name: "Pyxis", genitive: "Pyxidis", meaning: "The Compass",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "A mariner's compass added by La Caille near the old ship Argo — a small, faint line of three stars."),
        .init(abbr: "Col", name: "Columba", genitive: "Columbae", meaning: "The Dove",
              hemisphere: .southern, family: "Heavenly Waters",
              blurb: "The dove of Noah (or of the Argonauts), a modest figure flying south of Orion's hare and the greater dog."),

        // MARK: Bayer's southern birds (1603)
        .init(abbr: "Aps", name: "Apus", genitive: "Apodis", meaning: "The Bird-of-Paradise",
              hemisphere: .southern, family: "Bayer",
              blurb: "A bird of paradise near the south pole, one of the dozen southern constellations introduced by Dutch navigators around 1600."),
        .init(abbr: "Cha", name: "Chamaeleon", genitive: "Chamaeleontis", meaning: "The Chameleon",
              hemisphere: .southern, family: "Bayer",
              blurb: "A faint chameleon close to the south celestial pole, paired with the nearby fly Musca as if catching it with its tongue."),
        .init(abbr: "Dor", name: "Dorado", genitive: "Doradus", meaning: "The Goldfish",
              hemisphere: .southern, family: "Bayer",
              blurb: "The dolphinfish, notable above all for holding most of the Large Magellanic Cloud — a satellite galaxy of the Milky Way and home to the Tarantula Nebula."),
        .init(abbr: "Gru", name: "Grus", genitive: "Gruis", meaning: "The Crane",
              hemisphere: .southern, family: "Bayer",
              blurb: "A wading crane in the deep southern sky, its body a clear line of stars led by Alnair. Once part of neighbouring Piscis Austrinus."),
        .init(abbr: "Hyi", name: "Hydrus", genitive: "Hydri", meaning: "The Lesser Water Snake",
              hemisphere: .southern, family: "Bayer",
              blurb: "A small male water snake winding between the two Magellanic Clouds, near the south pole — not to be confused with the larger Hydra."),
        .init(abbr: "Ind", name: "Indus", genitive: "Indi", meaning: "The Indian",
              hemisphere: .southern, family: "Bayer",
              blurb: "A figure representing an indigenous hunter, drawn by Dutch navigators in the far southern sky. It holds Epsilon Indi, one of the nearest stars to the Sun."),
        .init(abbr: "Mus", name: "Musca", genitive: "Muscae", meaning: "The Fly",
              hemisphere: .southern, family: "Bayer",
              blurb: "The only insect among the constellations, a small fly just south of the Southern Cross in a dense field of Milky Way."),
        .init(abbr: "Pav", name: "Pavo", genitive: "Pavonis", meaning: "The Peacock",
              hemisphere: .southern, family: "Bayer",
              blurb: "A peacock in the deep south, its brightest star simply nicknamed 'Peacock.' Holds a fine bright globular cluster, NGC 6752."),
        .init(abbr: "Phe", name: "Phoenix", genitive: "Phoenicis", meaning: "The Phoenix",
              hemisphere: .southern, family: "Bayer",
              blurb: "The immortal firebird reborn from its ashes, the largest of the southern-bird constellations, near the river's end at Achernar."),
        .init(abbr: "Tuc", name: "Tucana", genitive: "Tucanae", meaning: "The Toucan",
              hemisphere: .southern, family: "Bayer",
              blurb: "A toucan in the far south, holding the Small Magellanic Cloud and 47 Tucanae — one of the grandest globular clusters in the entire sky."),
        .init(abbr: "Vol", name: "Volans", genitive: "Volantis", meaning: "The Flying Fish",
              hemisphere: .southern, family: "Bayer",
              blurb: "A flying fish near the south pole, drawn as if leaping from the sea ahead of the ship Argo's keel."),

        // MARK: La Caille's southern instruments (1763)
        .init(abbr: "Ant", name: "Antlia", genitive: "Antliae", meaning: "The Air Pump",
              hemisphere: .southern, family: "La Caille",
              blurb: "An air pump honouring the physics of vacuums — one of La Caille's faint, instrument-themed southern constellations with no bright stars."),
        .init(abbr: "Cae", name: "Caelum", genitive: "Caeli", meaning: "The Chisel",
              hemisphere: .southern, family: "La Caille",
              blurb: "An engraver's chisel, one of the smallest and faintest constellations, a couple of dim stars between Eridanus and Columba."),
        .init(abbr: "Cir", name: "Circinus", genitive: "Circini", meaning: "The Compasses",
              hemisphere: .southern, family: "La Caille",
              blurb: "A draughtsman's drawing compasses, a slim wedge of stars tucked beside the brilliant feet of Centaurus."),
        .init(abbr: "For", name: "Fornax", genitive: "Fornacis", meaning: "The Furnace",
              hemisphere: .southern, family: "La Caille",
              blurb: "A chemical furnace set in a bend of the river Eridanus. Faint to the eye, but a celebrated window onto deep space — site of the Hubble Ultra-Deep Field."),
        .init(abbr: "Hor", name: "Horologium", genitive: "Horologii", meaning: "The Pendulum Clock",
              hemisphere: .southern, family: "La Caille",
              blurb: "A pendulum clock honouring the timekeeping vital to astronomy, a long faint trail of stars beside Eridanus."),
        .init(abbr: "Men", name: "Mensa", genitive: "Mensae", meaning: "The Table Mountain",
              hemisphere: .southern, family: "La Caille",
              blurb: "Named for Cape Town's Table Mountain where La Caille observed, this is the faintest constellation of all — yet part of the Large Magellanic Cloud spills into it like the mountain's cloud."),
        .init(abbr: "Mic", name: "Microscopium", genitive: "Microscopii", meaning: "The Microscope",
              hemisphere: .southern, family: "La Caille",
              blurb: "A microscope marking the age of instruments, a dim quadrilateral of stars below Capricornus."),
        .init(abbr: "Nor", name: "Norma", genitive: "Normae", meaning: "The Carpenter's Square",
              hemisphere: .southern, family: "La Caille",
              blurb: "A set-square and rule, set in a dense and dusty stretch of the southern Milky Way between Scorpius and Centaurus."),
        .init(abbr: "Oct", name: "Octans", genitive: "Octantis", meaning: "The Octant",
              hemisphere: .southern, family: "La Caille",
              blurb: "The octant navigation instrument, important because it contains the south celestial pole — though its 'pole star,' Sigma Octantis, is barely visible."),
        .init(abbr: "Pic", name: "Pictor", genitive: "Pictoris", meaning: "The Painter's Easel",
              hemisphere: .southern, family: "La Caille",
              blurb: "An easel beside brilliant Canopus. Its star Beta Pictoris has a famous dusty disc with forming planets — a young solar system caught in the act."),
        .init(abbr: "Ret", name: "Reticulum", genitive: "Reticuli", meaning: "The Reticle",
              hemisphere: .southern, family: "La Caille",
              blurb: "The crosshair reticle of an eyepiece, a small diamond of stars near the Large Magellanic Cloud."),
        .init(abbr: "Scl", name: "Sculptor", genitive: "Sculptoris", meaning: "The Sculptor's Studio",
              hemisphere: .southern, family: "La Caille",
              blurb: "A sculptor's workshop, faint but pointing toward the south galactic pole, and home to the bright edge-on Sculptor Galaxy (NGC 253)."),
        .init(abbr: "Tel", name: "Telescopium", genitive: "Telescopii", meaning: "The Telescope",
              hemisphere: .southern, family: "La Caille",
              blurb: "A telescope honouring the instrument that remade astronomy, a sparse group of faint stars below Sagittarius and Corona Australis."),
    ]
}
